#!/usr/bin/env bash
#   _____ _____
#  |  _  |   __|  Piotr Serafin
#  |   __|__   |  https://piotrserafin.dev
#  |__|  |_____|  https://github.com/piotrserafin
#
# Opens newsboat article in firefox
/usr/bin/firefox "$@" & > /dev/null 2>&1

