#!/usr/bin/env bash
#   _____ _____
#  |  _  |   __|  Piotr Serafin
#  |   __|__   |  https://piotrserafin.dev
#  |__|  |_____|  https://github.com/piotrserafin
#

# Opens a basic yes/no prompt with dmenu
# This is useful for confirming whether an action should be taken
[ "$(printf "No\\nYes" | dmenu -i -p "$1")" = "Yes" ] && $2
